# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class Atr(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAtr(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Atr()
        x.Init(buf, n + offset)
        return x

    # Atr
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def AtrStart(builder): builder.StartObject(0)
def AtrEnd(builder): return builder.EndObject()
