# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class Chnl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsChnl(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Chnl()
        x.Init(buf, n + offset)
        return x

    # Chnl
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Chnl
    def ChannelName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Chnl
    def ObjectLabels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from ObjLbl import ObjLbl
            obj = ObjLbl()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Chnl
    def ObjectLabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ChnlStart(builder): builder.StartObject(2)
def ChnlAddChannelName(builder, ChannelName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ChannelName), 0)
def ChnlAddObjectLabels(builder, ObjectLabels): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ObjectLabels), 0)
def ChnlStartObjectLabelsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ChnlEnd(builder): return builder.EndObject()
