# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class keypnt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAskeypnt(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = keypnt()
        x.Init(buf, n + offset)
        return x

    # keypnt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def keypntStart(builder): builder.StartObject(0)
def keypntEnd(builder): return builder.EndObject()
