# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class Seq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSeq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Seq()
        x.Init(buf, n + offset)
        return x

    # Seq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Seq
    def SequenceDetails(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sequence_details import sequence_details
            obj = sequence_details()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Seq
    def Labels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Lab import Lab
            obj = Lab()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Seq
    def LabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SeqStart(builder): builder.StartObject(2)
def SeqAddSequenceDetails(builder, SequenceDetails): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(SequenceDetails), 0)
def SeqAddLabels(builder, Labels): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Labels), 0)
def SeqStartLabelsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SeqEnd(builder): return builder.EndObject()
