# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class sequence_details(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAssequence_details(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = sequence_details()
        x.Init(buf, n + offset)
        return x

    # sequence_details
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # sequence_details
    def FolderName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # sequence_details
    def FileName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def sequence_detailsStart(builder): builder.StartObject(2)
def sequence_detailsAddFolderName(builder, FolderName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(FolderName), 0)
def sequence_detailsAddFileName(builder, FileName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(FileName), 0)
def sequence_detailsEnd(builder): return builder.EndObject()
