# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pointcloud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pointcloud.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10pointcloud.proto\"$\n\x0ePointAttribute\x12\x12\n\npointValue\x18\x01 \x01(\x01\"0\n\x05Point\x12\'\n\x0epointAtributes\x18\x01 \x03(\x0b\x32\x0f.PointAttribute\"u\n\nPointCloud\x12\x11\n\tpointType\x18\x01 \x01(\t\x12\x12\n\ncloudWidth\x18\x02 \x01(\r\x12\x13\n\x0b\x63loudHeight\x18\x03 \x01(\r\x12\x13\n\x0bpointsCount\x18\x04 \x01(\r\x12\x16\n\x06points\x18\x05 \x03(\x0b\x32\x06.Point\"\xb3\x01\n\x16PointCloudDataResponse\x12\x19\n\x11recievedTimestamp\x18\x01 \x01(\x04\x12\x1b\n\x13responseChannelName\x18\x02 \x01(\t\x12\x1a\n\x12responseDeviceName\x18\x03 \x01(\t\x12\x11\n\tcloudName\x18\x04 \x01(\t\x12\x10\n\x08uniqueId\x18\x05 \x01(\x04\x12 \n\x0bpointClouds\x18\x06 \x03(\x0b\x32\x0b.PointCloudb\x06proto3')
)




_POINTATTRIBUTE = _descriptor.Descriptor(
  name='PointAttribute',
  full_name='PointAttribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pointValue', full_name='PointAttribute.pointValue', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=56,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pointAtributes', full_name='Point.pointAtributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=106,
)


_POINTCLOUD = _descriptor.Descriptor(
  name='PointCloud',
  full_name='PointCloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pointType', full_name='PointCloud.pointType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudWidth', full_name='PointCloud.cloudWidth', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudHeight', full_name='PointCloud.cloudHeight', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pointsCount', full_name='PointCloud.pointsCount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='PointCloud.points', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=225,
)


_POINTCLOUDDATARESPONSE = _descriptor.Descriptor(
  name='PointCloudDataResponse',
  full_name='PointCloudDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recievedTimestamp', full_name='PointCloudDataResponse.recievedTimestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseChannelName', full_name='PointCloudDataResponse.responseChannelName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseDeviceName', full_name='PointCloudDataResponse.responseDeviceName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudName', full_name='PointCloudDataResponse.cloudName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uniqueId', full_name='PointCloudDataResponse.uniqueId', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pointClouds', full_name='PointCloudDataResponse.pointClouds', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=407,
)

_POINT.fields_by_name['pointAtributes'].message_type = _POINTATTRIBUTE
_POINTCLOUD.fields_by_name['points'].message_type = _POINT
_POINTCLOUDDATARESPONSE.fields_by_name['pointClouds'].message_type = _POINTCLOUD
DESCRIPTOR.message_types_by_name['PointAttribute'] = _POINTATTRIBUTE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['PointCloud'] = _POINTCLOUD
DESCRIPTOR.message_types_by_name['PointCloudDataResponse'] = _POINTCLOUDDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointAttribute = _reflection.GeneratedProtocolMessageType('PointAttribute', (_message.Message,), dict(
  DESCRIPTOR = _POINTATTRIBUTE,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:PointAttribute)
  ))
_sym_db.RegisterMessage(PointAttribute)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUD,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:PointCloud)
  ))
_sym_db.RegisterMessage(PointCloud)

PointCloudDataResponse = _reflection.GeneratedProtocolMessageType('PointCloudDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUDDATARESPONSE,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:PointCloudDataResponse)
  ))
_sym_db.RegisterMessage(PointCloudDataResponse)


# @@protoc_insertion_point(module_scope)
